version: '3.8'

services:
  sap-sync:
    build: .
    ports:
      - "9000:9000"
    environment:
      # SAP B1 Configuration
      - SQL_PROXY_URL=${SQL_PROXY_URL}

      # MySQL Configuration
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}

      # Web UI Authentication
      - WEB_USERNAME=${WEB_USERNAME:-admin}
      - WEB_PASSWORD=${WEB_PASSWORD:-d1sapsync2024}
      - FLASK_SECRET_KEY=${FLASK_SECRET_KEY}

      # Sync Configuration
      - BATCH_SIZE=${BATCH_SIZE:-50}

      # Background Job Settings
      - BARCODE_SYNC_ENABLED=${BARCODE_SYNC_ENABLED:-true}
      - BARCODE_SYNC_AUTO_START=${BARCODE_SYNC_AUTO_START:-true}
      - BARCODE_SYNC_INTERVAL=${BARCODE_SYNC_INTERVAL:-300}
      - BARCODE_SYNC_AUTO_RESTART=${BARCODE_SYNC_AUTO_RESTART:-true}
      - BARCODE_SYNC_RESTART_DELAY=${BARCODE_SYNC_RESTART_DELAY:-60}
      - BARCODE_SYNC_MAX_RESTARTS=${BARCODE_SYNC_MAX_RESTARTS:-5}

      # Serial Number Sync Settings (if applicable)
      - SERIAL_SYNC_ENABLED=${SERIAL_SYNC_ENABLED:-true}
      - SERIAL_SYNC_AUTO_START=${SERIAL_SYNC_AUTO_START:-true}
      - SERIAL_SYNC_INTERVAL=${SERIAL_SYNC_INTERVAL:-900}
      - SERIAL_SYNC_AUTO_RESTART=${SERIAL_SYNC_AUTO_RESTART:-true}
      - SERIAL_SYNC_RESTART_DELAY=${SERIAL_SYNC_RESTART_DELAY:-60}
      - SERIAL_SYNC_MAX_RESTARTS=${SERIAL_SYNC_MAX_RESTARTS:-5}

      # Rolling Update Configuration
      - ROLLING_UPDATE_MODE=${ROLLING_UPDATE_MODE:-timestamp}
      - SYNC_INTERVAL_HOURS=${SYNC_INTERVAL_HOURS:-24}
      - FORCE_SYNC_DAYS=${FORCE_SYNC_DAYS:-7}
      - ADAPTIVE_BATCH_SIZE=${ADAPTIVE_BATCH_SIZE:-false}
      - MIN_BATCH_SIZE=${MIN_BATCH_SIZE:-10}
      - MAX_BATCH_SIZE=${MAX_BATCH_SIZE:-100}

      # Production Settings
      - FLASK_ENV=production
      - FLASK_DEBUG=false
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped

networks:
  default:
    name: sap-sync-network